# Pre-change validation - Creates a pre-change validation using a JSON file, waits for the result and evaluates it 
---

- name: Run Pre-change validation
  hosts: nd
  gather_facts: no

  vars:
    nd_login: &nd_login
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      #use_proxy: "{{ ansible_httpapi_use_proxy }}"
    ig_name: SiteGroup-ACI
    site_name: ACI-SJC23
    #git_commit_sha: "{{ lookup('ansible.builtin.env', 'GITHUB_SHA') }}"

  tasks:
    - name: Create a new Pre-Change Analysis from file
      cisco.nd.nd_pcv:
        <<: *nd_login
        ig_name: "{{ ig_name }}"
        site_name: "{{ site_name }}"
        name: "pcv"
        file: "brc-App_To_FW.xml"
        state: present
